### ISSUE TITLE
Web service not available

### ISSUE THREAD

**Issue by stefan-balke** [craffel/mir_eval#230] opened 2016-12-29 12:29 UTC
Hi,

since the webservice is not available we should either delete it from the README.md or setup some other resources for that.

Opinions?

**Comment by craffel** [comment] 2016-12-29 19:10
> we should either delete it from the README.md or setup some other resources for that.

Or we could, you know, fix the webservice!  This was caused by the labrosa webserver crashing and losing the appropriate apache configuration to successfully deploy the proxy to http://mireval.herokuapp.com/ (where the service actually lives).  Now fixed.

**Closed** 2016-12-29 19:11 UTC
